import type { MeddicccCategory, SpinCategory } from "./types";

export const OPEN_QUESTION_STARTERS = [
  "what",
  "how",
  "where",
  "why",
  "who",
  "which",
  "when",
  "walk me through",
  "tell me",
  "talk me through",
  "describe",
  "help me understand",
  "say more",
];

export const CLOSED_QUESTION_STARTERS = [
  "is",
  "are",
  "do",
  "does",
  "did",
  "can",
  "could",
  "would you like",
  "have you",
  "has",
  "will",
  "should",
  "was",
  "were",
];

export const EMPATHY_PHRASES = [
  "that makes sense",
  "makes sense",
  "i understand",
  "understood",
  "that is fair",
  "that's fair",
  "fair concern",
  "fair enough",
  "you are right",
  "you're right",
  "probably right",
  "i would",
  "i'd",
  "in your position",
  "i appreciate",
  "appreciate you",
  "thank you for",
  "that sounds",
  "sounds frustrating",
  "sounds painful",
  "right thing to",
  "right question",
  "good question",
  "taking that seriously",
  "take that seriously",
  "i hear",
  "no argument",
  "reasonable",
  "i would be",
  "i'd be",
  "honest",
];

export const DISMISSIVE_PHRASES = [
  "everyone says that",
  "everybody says that",
  "don't worry",
  "do not worry",
  "trust me",
  "that is not an issue",
  "that's not an issue",
  "that is not a problem",
  "that's not a problem",
  "you are wrong",
  "you're wrong",
  "actually, no",
  "that is incorrect",
  "not really a concern",
  "people get over",
  "get comfortable eventually",
];

export const SITUATION_LEXICON = [
  "today",
  "currently",
  "current",
  "process",
  "workflow",
  "how does",
  "how do you",
  "who",
  "tools",
  "steps",
  "typically",
  "usually",
  "how many",
  "how long",
  "team",
  "walk me through",
  "look like",
  "set up",
  "structure",
  "own",
];

export const PROBLEM_LEXICON = [
  "difficult",
  "hard",
  "stuck",
  "wait",
  "waiting",
  "slow",
  "slower",
  "fail",
  "failing",
  "bottleneck",
  "painful",
  "pain",
  "break",
  "breaks",
  "broken",
  "frustrat",
  "manual",
  "error",
  "delay",
  "longest",
  "friction",
  "tedious",
  "repetitive",
  "postponed",
  "gets in the way",
  "problem",
  "struggle",
  "step in",
  "take over",
  "gap",
];

export const IMPLICATION_LEXICON = [
  "cost",
  "costs",
  "costing",
  "impact",
  "consequence",
  "what does that mean",
  "what has that",
  "result",
  "quarter",
  "revenue",
  "miss",
  "missed",
  "slip",
  "slipped",
  "push out",
  "pushed out",
  "knock-on",
  "how much",
  "how many hours",
  "risk",
  "commitment",
  "commitments",
  "roadmap",
  "opportunity cost",
  "instead of",
  "not get to",
  "walk back",
  "pull back",
  "downstream",
  "per release",
  "per month",
  "annually",
  "a year",
];

export const NEED_PAYOFF_LEXICON = [
  "if that",
  "if this",
  "if you could",
  "would that",
  "what would it mean",
  "what would that",
  "value",
  "worth",
  "enable",
  "able to take on",
  "free up",
  "get back",
  "help you",
  "difference would",
  "better off",
  "upside",
  "eased",
  "improved",
];

export const MEDDICCC_LEXICON: Record<MeddicccCategory, string[]> = {
  metrics: [
    "metric",
    "measure",
    "number",
    "baseline",
    "hours",
    "days",
    "percent",
    "track",
    "kpi",
    "how would you know",
    "data",
    "cycle time",
    "latency",
  ],
  economicBuyer: [
    "budget",
    "approve",
    "approval",
    "sign off",
    "sign-off",
    "spend",
    "who else is involved",
    "cfo",
    "authority",
    "funds",
    "fund",
  ],
  decisionCriteria: [
    "criteria",
    "evaluate",
    "requirement",
    "would have to prove",
    "comfortable",
    "bar",
    "standard",
    "what would you need",
    "need to see",
  ],
  decisionProcess: [
    "next step",
    "next steps",
    "process",
    "steps",
    "who is involved",
    "who has to",
    "review board",
    "architecture review",
    "after that",
    "timeline",
    "stages",
  ],
  identifyPain: [
    "urgent",
    "this quarter",
    "biggest problem",
    "actually causing",
    "keeps you up",
    "most acute",
    "priority",
    "pain",
  ],
  champion: [
    "champion",
    "who feels",
    "advocate",
    "internally",
    "most acutely",
    "sponsor",
    "who would push",
    "on your team",
  ],
  competition: [
    "alternative",
    "other tools",
    "copilot",
    "already use",
    "instead",
    "do nothing",
    "did nothing",
    "in-house",
    "build it yourself",
    "contractors",
    "competitor",
    "vendor",
  ],
  paperProcess: [
    "security review",
    "procurement",
    "legal",
    "contract",
    "paperwork",
    "vendor onboarding",
    "compliance review",
    "documentation",
    "in parallel",
  ],
  compellingEvent: [
    "deadline",
    "by when",
    "date",
    "urgency",
    "compliance deadline",
    "launch",
    "freeze",
    "next quarter",
    "more urgent",
  ],
};

export const SPIN_LEXICON: Record<SpinCategory, string[]> = {
  situation: SITUATION_LEXICON,
  problem: PROBLEM_LEXICON,
  implication: IMPLICATION_LEXICON,
  needPayoff: NEED_PAYOFF_LEXICON,
};

/** Accurate, defensible Devin and engineering vocabulary. */
export const ACCURATE_TERMS = [
  "pull request",
  "branch",
  "repository",
  "repo",
  "code review",
  "reviewer",
  "tests",
  "test suite",
  "linter",
  "lint",
  "ci",
  "pipeline",
  "feature flag",
  "rollback",
  "knowledge note",
  "playbook",
  "blueprint",
  "environment",
  "diff",
  "plan",
  "scoped",
  "bounded",
  "review process",
  "merge",
  "deploy",
  "audit",
  "least privilege",
  "browser",
  "recording",
  "self-review",
  "migration",
];

/** Claims that are too strong to defend. */
export const UNSUPPORTED_CLAIM_PATTERNS: { pattern: RegExp; why: string }[] = [
  {
    pattern: /\bguarantee[sd]?\b/i,
    why: "'Guarantee' is a promise you cannot honour about software behaviour.",
  },
  {
    pattern: /\b100\s?%|\bzero (risk|bugs|defects)\b/i,
    why: "Absolute figures like 100% or zero risk are not defensible.",
  },
  {
    pattern: /\bnever (fails|breaks|makes mistakes|introduces)\b/i,
    why: "'Never fails' is an absolute claim a technical buyer will immediately test.",
  },
  {
    pattern: /\bcompletely (secure|safe)\b|\bfully secure\b/i,
    why: "No system is 'completely secure'; describe controls instead.",
  },
  {
    pattern: /\b(\d{1,3})\s?%\s?(faster|more productive|productivity|cost reduction|savings)/i,
    why: "A productivity percentage without their own baseline will not survive a budget review.",
  },
  {
    pattern: /\b(10x|5x|3x)\b/i,
    why: "Multiplier claims read as marketing and invite a fight you cannot win.",
  },
  {
    pattern: /\breplaces? (your )?(engineers|developers|the team)\b/i,
    why: "Replacement framing loses engineering leaders and their teams.",
  },
  {
    pattern: /\bno (code )?review (is )?(needed|necessary|required)\b|\bwithout review\b/i,
    why: "Claiming review is unnecessary contradicts the workflow and destroys credibility.",
  },
  {
    pattern: /\bdeploys? (straight |directly )?to production\b|\bautomatically deploys\b/i,
    why: "Devin's work goes through the customer's existing review and release process.",
  },
  {
    pattern: /\beliminates?\b/i,
    why: "'Eliminates' overstates; describe what it reduces and what remains.",
  },
  {
    pattern: /\bhandles? (any|every) (codebase|repository|task)\b/i,
    why: "Claiming it handles anything contradicts naming honest limits.",
  },
  {
    pattern: /\bfully autonomous\b|\bno human\b/i,
    why: "Human review is part of the workflow; do not sell it away.",
  },
];

export const PITCH_MARKERS = [
  "devin can",
  "devin will",
  "our product",
  "our platform",
  "the platform",
  "we offer",
  "our solution",
  "feature",
  "capabilities",
  "let me show you",
  "unlike",
];

export const NEXT_STEP_MARKERS = [
  "next step",
  "would it help",
  "shall we",
  "should we",
  "propose",
  "suggest we",
  "let us",
  "let's",
  "30 minutes",
  "thirty minutes",
  "in parallel",
  "start with",
  "first task",
  "pilot",
  "trial",
  "evaluation",
  "put time",
  "diary",
  "calendar",
  "send",
  "follow up",
  "who should",
  "bring in",
  "get you in front of",
];
